=== diacus/wfc/wfc/assets/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "Script",
  "description": "A bot script",
  "type": "object",
  "required": ["dialogs", "version"],
  "additionalProperties": false,
  "properties": {
    "version": {
      "description": "The version of this Script",
      "type": "string",
      "enum": ["2.0.0"]
    },
    "nlp_fallback": {
      "description": "What the bot will say when NLP doesn't recognize an intent",
      "type": "string"
    },
    "qna_followup": {
      "description": "The dialog the bot will go to after responding a question with the qna service",
      "type": "string",
      "minLength": 1
    },
    "unexpected_error_dialog": {
      "description": "what the bot will say when an unexpected error happens",
      "type": "string"
    },
    "intentions": {
      "description": "List of intentions that can be spotted by the NLP Engine",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "dialog": {
            "type": "string"
          },
          "examples": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": ["name"],
        "additionalProperties": false
      }
    },
    "commands": {
      "description": "List of commands that can be spotted by the Bot",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "keyword": {
            "type": "string"
          },
          "dialog": {
            "type": "string"
          }
        },
        "required": ["keyword", "dialog"],
        "additionalProperties": false
      }
    },
    "entities": {
      "description": "List of possible entities contained in this script",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          }
        },
        "required": ["name"],
        "additionalProperties": false
      }
    },
    "qa": {
      "description": "List of Questions and its respective Answers",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "question": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "answer": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": ["question", "answer"],
        "additionalProperties": false
      }
    },
    "dialogs": {
      "description": "List of bot Script available Dialogs",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1
          },
          "actions": {
            "description": "List of Actions a Dialog will execute",
            "type": "array",
            "items": {
              "oneOf": [
                { "$ref": "#/definitions/sendText" },
                { "$ref": "#/definitions/waitInput" },
                { "$ref": "#/definitions/changeDialog" },
                { "$ref": "#/definitions/callIntegration" },
                { "$ref": "#/definitions/openFlow" },
                { "$ref": "#/definitions/setVar" },
                { "$ref": "#/definitions/sendMenu" },
                { "$ref": "#/definitions/sendCarousel" },
                { "$ref": "#/definitions/sendMedia" },
                { "$ref": "#/definitions/subscribeFeed" },
                { "$ref": "#/definitions/unsubscribeFeed" },
                { "$ref": "#/definitions/askForInput" },
                { "$ref": "#/definitions/handoff" },
                { "$ref": "#/definitions/if" }
              ],
              "properties": {
                "id": {
                  "type": "string",
                  "minLength": 1
                },
                "condition": {
                  "$ref": "#/definitions/expression"
                }
              }
            },
            "required": ["id", "action"],
            "additionalProperties": false
          }
        },
        "required": ["name", "actions"],
        "additionalProperties": false
      }
    }
  },
  "definitions": {
    "buttons": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "label": {
            "type": "string",
            "minLength": 1
          },
          "payload": {
            "type": [
              "object",
              "string"
            ]
          },
          "type": {
            "type": "string",
            "minLength": 1
          },
          "flow": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "label"
        ]
      }
    },
    "sendText": {
      "properties": {
        "text": {
          "type": "string",
          "minLength": 1
        },
        "one_of": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          },
          "minItems": 1
        },
        "action": {
          "enum": ["send_text"]
        }
      },
      "required": ["action"]
    },
    "waitInput": {
      "properties": {
        "var_name": {
          "type": "string",
          "minLength": 1
        },
        "action": {
          "enum": ["wait_input"]
        },
        "expect": {
          "type": "object",
          "properties": {
            "entities": {
              "type": "array",
              "items": {
                "type": "string",
                "minLength": 1
              },
              "minItems": 1
            },
            "attachment_types": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "minItems": 1
            },
            "payload": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "fallback": {
              "type": "string",
              "minLength": 1
            }
          },
          "additionalProperties": {
            "type": "object",
            "properties": {
              "can_switch_content": {
                "type": "boolean"
              }
            }
          },
          "required": ["fallback"]
        }
      },
      "required": ["action", "var_name"]
    },
    "openFlow": {
      "properties": {
        "flow": {
          "type": "string",
          "minLength": 1
        },
        "action": {
          "enum": ["open_flow"]
        }
      },
      "required": ["action", "flow"]
    },
    "setVar": {
      "properties": {
        "var_name": {
          "type": "string",
          "minLength": 1
        },
        "value": {
          "minLength": 1
        },
        "action": {
          "enum": ["set_var"]
        }
      },
      "required": ["var_name", "value", "action"]
    },
    "changeDialog": {
      "properties": {
        "dialog": {
          "type": "string",
          "minLength": 1
        },
        "action": {
          "enum": ["change_dialog"]
        }
      },
      "required": ["action", "dialog"]
    },
    "callIntegration": {
      "properties": {
        "integration": {
          "type": "string",
          "minLength": 1
        },
        "function": {
          "type": "string",
          "minLength": 1
        },
        "function_params": {
          "type": "array",
          "items": {
            "minLength": 1
          }
        },
        "action": {
          "enum": ["call_integration"]
        },
        "errors": {
          "type": "object",
          "patternProperties": {
            "^on_": {
              "type": "object",
              "properties": {
                "jump": {
                  "type": "string"
                }
              },
              "additionalProperties": false,
              "required": ["jump"]
            }
          },
          "minProperties": 1
        }
      },
      "required": ["integration", "function", "function_params", "action"],
      "additionalItems": false
    },
    "sendMenu": {
      "properties": {
        "text": {
          "type": "string",
          "minLength": 1
        },
        "buttons": {
          "$ref": "#/definitions/buttons"
        },
        "action": {
          "enum": ["send_menu"]
        }
      },
      "required": ["action", "buttons"]
    },
    "sendCarousel": {
      "properties": {
        "content_source": {
          "type": "string",
          "minLength": 2
        },
        "action": {
          "enum": ["send_carousel"]
        },
        "card_content": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string",
              "minLength": 2
            },
            "description": {
              "type": "string",
              "minLength": 2
            },
            "image_url": {
              "type": "string",
              "minLength": 2
            },
            "buttons": {
              "$ref": "#/definitions/buttons"
            }
          },
          "required": ["title"],
          "additionalProperties": false
        },
        "cards": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "title": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "image_url": {
                "type": "string"
              },
              "buttons": {
                "$ref": "#/definitions/buttons"
              }
            },
            "required": ["title"]
          }
        }
      },
      "oneOf": [{
        "required": ["action", "cards"]
      }, {
      "required": ["action", "content_source", "card_content"]
      }]
    },
    "askForInput": {
      "properties": {
        "text": {
          "type": "string",
          "minLength": 1
        },
        "var_name": {
          "type": "string",
          "minLength": 1
        },
        "quick_replies": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          },
          "minItems": 1
        },
        "action": {
          "enum": ["ask_for_input"]
        },
        "expect": {
          "type": "object",
          "properties": {
            "entities": {
              "type": "array",
              "items": {
                "type": "string",
                "minLength": 1
              },
              "minLength": 1
            },
            "fallback": {
              "type": "string",
              "minLength": 1
            }
          },
          "required": ["entities", "fallback"]
        }
      },
      "required": ["action", "var_name", "text"]
    },
    "sendMedia": {
      "properties": {
        "url": {
          "type": "string"
        },
        "media_id": {
          "type": "string"
        },
        "buttons": {
          "$ref": "#/definitions/buttons"
        },
        "action": {
          "enum": ["send_media"]
        }
      },
      "oneOf": [{
        "required": ["action", "media_type", "url"]
      }, {
      "required": ["action", "media_type", "media_id"]
      }]
    },
    "subscribeFeed": {
      "properties": {
        "feed": {
          "type": "string",
          "minLength": 1
        },
        "action": {
          "enum": ["subscribe_feed"]
        }
      },
      "required": ["action", "feed"]
    },
    "unsubscribeFeed": {
      "properties": {
        "feed": {
          "type": "string",
          "minLength": 1
        },
        "action": {
          "enum": ["unsubscribe_feed"]
        }
      },
      "required": ["action", "feed"]
    },
    "handoff": {
      "properties": {
        "assignee": {
          "type": "string",
          "minLength": 1
        },
        "action": {
          "enum": ["handoff"]
        }
      },
      "required": ["action", "assignee"]
    },
    "unaryOperators": {
      "type": "string",
      "enum": ["is_empty", "is_not_empty"]
    },
    "if": {
      "properties": {
        "then": {
          "type": "string",
          "minLength": 1
        },
        "else": {
          "type": "string",
          "minLength": 1
        },
        "action": {
          "enum": ["if"]
        }
      },
      "required": ["action", "condition", "then"]
    },
    "binaryOperators": {
      "type": "string",
      "enum": ["equal", "not_equal", "has_entity"]
    },
    "operands": {
      "anyOf": [
        { "type": "string" },
        { "type": "boolean" },
        { "type": "number" },
        { "$ref": "#/definitions/expression" }
      ]
    },
    "operators": {
      "anyOf": [
        { "$ref": "#/definitions/unaryOperators" },
        { "$ref": "#/definitions/binaryOperators" }
      ]
    },
    "expression": {
      "type": "array",
      "items": [
        { "$ref": "#/definitions/operands" },
        { "$ref": "#/definitions/operators" },
        { "$ref": "#/definitions/operands" }
      ],
      "minItems": 2,
      "maxItems": 3
    }
  }
}

=== diacus/wfc/tests/samples/arithmetic-200.json
{
  "version": "2.0.0",
  "intentions": [],
  "entities": [],
  "dialogs": [
    {
      "name": "math",
      "actions": [
        {
          "action": "set_var",
          "var_name": "start",
          "value": 1
        },
        {
          "action": "set_var",
          "var_name": "start",
          "value": [
            "$start",
            "+",
            1
          ]
        },
        {
          "action": "set_var",
          "var_name": "start",
          "value": [
            "$start",
            "-",
            1
          ]
        },
        {
          "action": "set_var",
          "var_name": "start",
          "value": [
            "$start",
            "*",
            1
          ]
        },
        {
          "action": "set_var",
          "var_name": "start",
          "value": [
            "$start",
            "/",
            1
          ]
        }
      ]
    }
  ],
  "qa": []
}

=== diacus/wfc/tests/samples/ask.json
{
  "version": "2.0.0",
  "intentions": [],
  "entities": [],
  "dialogs": [
    {
      "name": "onboarding",
      "actions": [
        {
          "text": "Some question",
          "action": "ask_for_input",
          "var_name": "response"
        },
        {
          "action": "send_text",
          "text": "The response is: {{$response}}"
        },
        {
          "text": "Some other question",
          "action": "ask_for_input",
          "var_name": "response",
          "can_switch_context": false
        }
      ]
    }
  ],
  "qa": []
}

=== diacus/wfc/tests/samples/set-array-var-200.json
{
  "version": "2.0.0",
  "intentions": [],
  "entities": [],
  "dialogs": [
    {
      "name": "hola",
      "actions": [
        {
          "action": "set_var",
          "var_name": "name",
          "value": [
            "Max Power"
          ]
        },
        {
          "action": "set_var",
          "var_name": "nameAndAge",
          "value": [
            "Max Power",
            36
          ]
        },
        {
          "action": "set_var",
          "var_name": "height",
          "value": {
            "feets": 5,
            "inches": 7
          }
        },
        {
          "action": "set_var",
          "var_name": "nameAgeAndHeight",
          "value": [
            "Max Poser",
            36,
            "$height"
          ]
        }
      ]
    }
  ],
  "qa": []
}

=== diacus/wfc/tests/samples/commands-200.json
{
  "version": "2.0.0",
  "intentions": [],
  "entities": [],
  "commands": [
    {
      "keyword": "/help",
      "dialog": "entry_point_flow"
    }
  ],
  "dialogs": [
    {
      "name": "entry_point_flow",
      "actions": [
        {
          "action": "send_text",
          "text": "This is a test flow"
        }
      ]
    }
  ],
  "qa": []
}

=== diacus/wfc/tests/samples/qna-flow-200.json
{
  "version": "2.0.0",
  "intentions": [],
  "entities": [],
  "dialogs": [
    {
      "name": "greeting",
      "actions": [
        {
          "action": "send_text",
          "text": "Hello"
        }
      ]
    },
    {
      "name": "helpful",
      "actions": [
        {
          "action": "send_text",
          "text": "This is the QNA flow"
        }
      ]
    }
  ],
  "qa": [],
  "qna_followup": "helpful"
}

=== diacus/wfc/tests/samples/wait-keeping-context-200.json
{
  "version": "2.0.0",
  "intentions": [],
  "entities": [],
  "dialogs": [
    {
      "name": "onboarding",
      "actions": [
        {
          "action": "wait_input",
          "var_name": "input",
          "can_switch_context": false
        },
        {
          "action": "send_text",
          "text": "You just said '{{$input}}'"
        }
      ]
    }
  ],
  "qa": []
}

=== diacus/wfc/tests/samples/set-member-var-200.json
{
  "version": "2.0.0",
  "intentions": [],
  "entities": [],
  "dialogs": [
    {
      "name": "hola",
      "actions": [
        {
          "action": "set_var",
          "var_name": "persona",
          "value": {
            "name": "Homer J. Simpson",
            "age": 36
          }
        },
        {
          "action": "set_var",
          "var_name": "persona.name",
          "value": "Max Power"
        },
        {
          "action": "set_var",
          "var_name": "persona.address",
          "value": {
            "city": "Springfield",
            "street": "Evergreen",
            "number": 742
          }
        }
      ]
    }
  ],
  "qa": []
}

=== diacus/wfc/tests/samples/menu.json
{
  "version": "2.0.0",
  "intentions": [],
  "entities": [],
  "dialogs": [
    {
      "name": "main",
      "actions": [
        {
          "buttons": [
            {
              "label": "Details",
              "payload": {
                "id": "{{$nerd_id}}"
              },
              "type": "postback"
            },
            {
              "label": "Something",
              "payload": "Any random text",
              "type": "postback"
            },
            {
              "label": "ping",
              "payload": "pong",
              "type": "message"
            },
            {
              "label": "More Details",
              "payload": "http://www.wizeline.com/profile",
              "type": "open_url"
            }
          ],
          "action": "send_menu"
        }
      ]
    },
    {
      "name": "other_menu",
      "actions": [
        {
          "buttons": [
            {
              "label": "Option1",
              "payload": {
                "option_id": "foo"
              },
              "type": "postback"
            },
            {
              "label": "Option2",
              "payload": {
                "option_id": "bar"
              },
              "type": "postback"
            }
          ],
          "text": "Please choice an option",
          "action": "send_menu"
        }
      ]
    }
  ],
  "qa": []
}
